/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.github.fussel178.telestion.extension.corfu;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
